src/compas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("compasweb.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/compasweb/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from .views.published_job.published_job import KeywordView, DatasetDetailView, ModelDetailView, ModelCustomView, placeholder_functional_view
from .views.common import index, about
from .views.compas_model_run.compas_model_run import (
    run_compas_model,
    compas_model_output,
    download_compas_output_as_tar,
)

urlpatterns = [
    url(r"^$", index, name="homepage"),
    url(r"^about/", about, name="about"),
    path("published/", KeywordView.as_view(), name="published_job"),
    path("published/<str:keyword_filter>/", KeywordView.as_view(), name="published_job"),
    path(
        "dataset/<int:pk>/",
        DatasetDetailView.as_view(),
        name="dataset_detail",
    ),
    path("model/<int:pk>/", placeholder_functional_view, name="model_detail"),
    path("model/new/", run_compas_model, name="run_compas_model"),
    path("model/output/<int:model_id>/", compas_model_output, name="compas_model_output"),
    path(
        "model/output/<int:model_id>/output.tar.gz",
        download_compas_output_as_tar,
        name="download_compas_output_as_tar",
    ),
]

src/compasweb/models.py
import os
import math

from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from django.core.files.uploadedfile import UploadedFile

import tarfile
from bokeh.embed import server_document
import h5py
import numpy as np

from .utils.constants import *
from .utils.plotting_functions import *


class Keyword(models.Model):
    tag = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        return self.tag


def job_directory_path(instance, filename):
    """
    a callable to generate a custom directory path to upload file to
    instance: an instance of the model to which the file belongs
    filename: name of the file to be uploaded
    """
    # change file name if it has spaces
    fname = filename.replace(" ", "_")
    dataset_id = str(instance.compasjob.id)
    model_id = str(instance.compasmodel.id)
    # dataset files will be saved in MEDIA_ROOT/datasets/dataset_id/model_id/
    return os.path.join("datasets", dataset_id, model_id, fname)

def grabSubGroup(file, key):
    subgroup = file[key]
    print(list(subgroup.keys()))
    return list(subgroup.keys())


class COMPASJob(models.Model):
    author = models.CharField(max_length=255, blank=False, null=False)
    # published defines if the job was published in a journal/arxiv
    published = models.BooleanField(default=False)
    title = models.CharField(max_length=255, blank=False, null=False)
    year = models.IntegerField(null=True)
    journal = models.CharField(max_length=255, null=True)
    journal_DOI = models.CharField(max_length=255, null=True)
    dataset_DOI = models.CharField(max_length=255, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True, null=True)
    # public defines if the job is publicly accessible
    public = models.BooleanField(default=False)
    download_link = models.TextField(blank=True, null=True)
    arxiv_id = models.CharField(max_length=255, blank=False)
    keywords = models.ManyToManyField(Keyword)

    @classmethod
    def filter_by_keyword(cls, keyword=None):
        return cls.objects.all().filter(keywords__tag=keyword) if keyword else cls.objects.all()

    def __str__(self):
        return self.title


class COMPASModel(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    summary = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class COMPASDatasetModel(models.Model):
    compasjob = models.ForeignKey(COMPASJob, models.CASCADE)
    compasmodel = models.ForeignKey(COMPASModel, models.CASCADE)
    files = models.FileField(upload_to=job_directory_path, blank=True, null=True)

    def __str__(self):
        return f"{self.compasjob.title} - {self.compasmodel.name}"

    def save(self, *args, **kwargs):
        """
        overwrites default save behavior
        """
        super().save(*args, **kwargs)
        # Check file name is not empty after saving the model and uploading file
        if self.files.name:
            # Check the uploaded file could be decompressed using tarfile
            if tarfile.is_tarfile(self.files.path):
                self.decompress_tar_file()
            # If the uploaded file is an individual file
            else:
                self.create_upload(self.files.name)

    def decompress_tar_file(self):
        # Get the actual path for uploaded file
        dataset_dir = os.path.dirname(self.files.path)
        dataset_tar = tarfile.open(self.files.path)
        # dataset_tar.extractall(dataset_dir)
        for member in dataset_tar.getmembers():
            # ignore any directory but include its contnets
            if not member.isdir():
                # extract files into dataset directory (this will create subdirectories as well, exactly as in the tarball)
                dataset_tar.extract(member, dataset_dir)
                self.create_upload(os.path.join(os.path.dirname(self.files.name), member.name))
        dataset_tar.close()
        # remove the tar file after decompression
        os.remove(self.files.path)

    # create an Upload model for an uploaded file
    def create_upload(self, filepath):
        """
        filepath is the relative path of the uploaded file within MEDIA_ROOT
        """
        upload = Upload()
        upload.file = filepath
        upload.datasetmodel = self
        upload.save()

    def get_rundetails(self):
        """
        query file: "run_details.txt"
        """
        return self.upload_set.filter(file__iendswith="Run_Details.txt")

    def get_data(self):
        """
        query file: "*.h5"
        """
        return self.upload_set.filter(file__iendswith=".h5")


class Upload(models.Model):
    file = models.FileField(blank=True, null=True)
    datasetmodel = models.ForeignKey(COMPASDatasetModel, models.CASCADE)

    def __str__(self):
        return os.path.basename(self.file.name)

    def get_content(self):
        """
        get the content of a file; will be called only on txt files
        """
        if self.file.storage.exists(self.file.name):

            with self.file.open("r") as f:
                return f.read()
        else:
            return "File not found"

    def get_plots(self, input, is_mobile=False):
        if input:
            script = server_document(settings.BOKEH_SERVER, arguments={"filename": input, "is_mobile": is_mobile})
        else:
            script = "<p>No data was provided for plots</p>"
            return script

    def get_react_keys(self):

        first_file = h5py.File(self.file, 'r')
        first_keys = {}
        first_keys["menu"] = list(first_file.keys())

        return first_keys

    def return_react_subgroup(self, request):

        first_file = h5py.File(self.file, 'r')
        main_group = request.POST.get("main_group")
        subgroup_list = grabSubGroup(first_file, main_group)

        total_length = first_file[main_group][subgroup_list[0]].shape[0]
        
        if(total_length > 1e6):
            strided_length = int(total_length/5e5)
        else:
            strided_length = 1

        file_length = int(np.ceil(total_length/strided_length))

        initial_values = [0,1]

        default_values = default_prefs[default_prefs[:,0] == main_group]

        if(default_values.any()):
            default_values = default_values[0][1]
            if(np.isin(default_values, subgroup_list).all()):
                initial_values = [int(np.where(np.asarray(subgroup_list) == default_values[0])[0][0]), int(np.where(np.asarray(subgroup_list) == default_values[1])[0][0])] 

        context = {
            "subgroup_list": subgroup_list,
            "subgroup_init": initial_values,
            "num_samples": [int(file_length), int(total_length)],
            "strided_length": strided_length,
        }

        return context

    def return_react_data(self, request):
        main_group, subgroup_1, subgroup_2, strided_length = request.POST.getlist("data_request")

        first_file = h5py.File(self.file, 'r')
        strided_length = int(strided_length)

        total_length = first_file[main_group][subgroup_1].shape[0]
        file_length = int(np.ceil(total_length/strided_length))

        data_json = dataQuery(first_file, main_group, subgroup_1, subgroup_2, strided_length)

        context = {"trunc_data": data_json,
                   "num_samples": [int(file_length), int(total_length)],
        }

        return context

    def read_stats(self):
        """
        read data length in h5 file
        """
        data_stats = {}

        if self.file.storage.exists(self.file.name):
            data = h5py.File(self.file, "r")
            for key in data.keys():
                prim_key = list(data[key])[0]
                stat = len(data[key][prim_key])
                data_stats[key] = stat

        return data_stats


class COMPASModelRun(models.Model):

    # required input parameters
    # --initial-mass-1
    mass1 = models.FloatField(
        blank=False,
        null=False,
        default=0.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(150.0)],
        help_text="Mass of the initially more massive star.  0 < Value < 150",
    )
    # --initial-mass-2
    mass2 = models.FloatField(
        blank=False,
        null=False,
        default=0.1,
        validators=[MinValueValidator(0.1), MaxValueValidator(150.0)],
        help_text="Mass of the initially less massive star. 0 < Value < 150",
    )
    # --metalicity
    metallicity = models.FloatField(
        blank=False,
        null=False,
        default=0.0142,
        validators=[MinValueValidator(1e-4), MaxValueValidator(0.03)],
        help_text="Metallicity of stars.  1E-4 < Value < 0.03",
    )
    # --eccentricity
    eccentricity = models.FloatField(
        blank=False,
        null=False,
        default=0.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(1)],
        help_text="Orbital eccentricity of the binary. 0 <= Value < 1",
    )
    # --semi_major_axis
    separation = models.FloatField(
        blank=True,
        null=True,
        validators=[MinValueValidator(0.0)],
        help_text="Value > 0",
    )
    # --orbital_period
    orbital_period = models.FloatField(
        blank=True,
        null=True,
        validators=[MinValueValidator(0.0)],
        help_text="Value > 0",
    )
    # --maximum-evolution-time
    max_time = models.FloatField(
        blank=False,
        null=False,
        default=0,
        validators=[MinValueValidator(0.0), MaxValueValidator(1400)],
        help_text="Maximum time to evolve binary for. 0 < Value <= 1400",
    )

    # advanced settings
    # kicks
    kick_enabled = models.BooleanField(default=False)
    common_envelope_enabled = models.BooleanField(default=False)

src/compasweb/views/common.py
# import logging
# logger = logging.getLogger(__name__)
# from django.http import Http404
# from django.contrib import messages
# from django.contrib.auth.decorators import login_required
# from django.db.models import Q
# from django.shortcuts import redirect, get_object_or_404
# from django.core.paginator import Paginator

from django.shortcuts import render, render_to_response
from django.views import generic


def index(request):
    """
    Render the index view.
    :param request: Django request object.
    :return: Rendered template
    """
    return render(
        request,
        "compasweb/common/index.html",
    )


def about(request):
    """
    Render the about view.
    :param request: Django request object.
    :return: Rendered template
    """
    return render(
        request,
        "compasweb/common/about.html",
    )


# def error_404_view(request, exception, template_name="compasweb/common/error_404.html"):
#     response = render_to_response(template_name)
#     response.status_code = 404
#     return response


# def job_table(request):
#
#     current_jobs = COMPASJob.objects.order_by('year')
#     keyword_list = Keyword.objects.order_by('tag')
#
#     return render(
#         request,
#         "compasweb/job/job_table.html",
#         {
#             'jobs': current_jobs,
#             'keywords': keyword_list
#         }
#     )

src/compasweb/templates/compasweb/published_job/dataset_detail.html
{% extends 'compasweb/base/base.html' %}
{% load static %}

{% block page_header %}
<h1>Published COMPAS Models</h1>
{%endblock page_header%}

{% block content %}

<!-- Dataset information card on the top -->

<div class="card">
    <h3 class="card-header">Dataset</h3>
    <div class="card-body">
      <p class="p-text-md">
        <div class="div-text-sm"><span class="div-text-sm-underline">Title:</span> {{ job.title }}</div>
        <div class="div-text-sm"><span class="div-text-sm-underline">Author:</span> {{ job.author }}</div>
        <div class="div-text-sm"><span class="div-text-sm-underline">Creation Date:</span> {{ job.creation_time }}</div>
        <div class="div-text-sm"><span class="div-text-sm-underline">Description:</span> {{ job.description }}</div>
    </p>
    </div>
  </div>
  
<!-- table title -->
<div class="title-md">
    <h2 class="text-left ">Models</h2>
    <hr class="dashed-line">
</div>

{% if job.compasdatasetmodel_set.exists %}
<!-- dataset models table -->
<div id="datasetmodels-table" class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr class="d-flex">
                <th class="col-2">Model</th>
                <th class="col-8">Summary</th>
                <th class="col-2">Details</th>
            </tr>
        </thead>

        {% for datasetmodel in job.compasdatasetmodel_set.all %}
        <tr scope="row" class="d-flex">
            <td class="col-2">{{ datasetmodel.compasmodel.name }}</td>
            <td class="col-8">{{ datasetmodel.compasmodel.summary }}</td>
            <td class="col-2 flex-cell-center">
                <a class="btn btn btn-dark"
                        href="{% url 'model_detail' datasetmodel.id %}">Explore</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% else %}
No Models
{% endif %}

<!-- navigate back to datasets page -->
<div>
    <a class="btn btn btn-dark btn-nav-back"
                        href="{% url 'published_job' %}">Back to Datasets</a>
</div>

{% endblock content %}

src/compasweb/templates/compasweb/published_job/job_datasets.html
{% extends 'compasweb/base/base.html' %}
{% block page_header %}
<h1>Published COMPAS Models</h1>
{%endblock page_header%}

{% block content %}

<!-- information card on the top -->
<div class="jumbotron info-card">
  <h3 class="jumbotron-heading text-left title-sm">Instructions</h3>
  <hr class="dashed-line">
  <!-- <p class="p-text-md"><span>How to explore the datasets</span>: -->
  <div class="container">
    <p>
      This page provides access to published datasets produced using COMPAS. The table below is organised by publication (see below for details on how to search amongst the models). Many papers present multiple models, which are shown on a second page. You can then click through to see the specific details and results associated with that model, including an interactive plotting page. All results can be downloaded and used in further publications.
<br/><br/>
We provide a list of predetermined tags (acronyms defined below) which can be used to quickly sort for relevant datasets. For example, select "BBH" to select all publications which study binary black holes.
<br/><br/>

Acronyms:<br/>
BBH   = Binary black hole<br/>
CE      = Common Envelope<br/>
SN      = Supernovae<br/>
GW    = Gravitational waves<br/>
DNS   = Double neutron star
NSBH = Neutron star-black holes
<br/><br/>
To sort by a particular column (e.g. author name or publication year), click the corresponding column header.
<br/><br/>
To view details of the data available associated with a particular publication, click "View" in the models column.

    </p>
  </div>
  <!-- <span>Plots</span>: different types of plots (grouped by physics) -->
  </p>
</div>

<!-- table title -->
<div class="title-md">
  <h2 class="text-left ">Datasets</h2>
  <hr class="dashed-line">
</div>

<!-- filters -->
<div class="container">
  <form class="form-group row" action="" method="get">
    <label id="KeywordLabel" for="keywords">Keyword Filter</lablel>
      <div class="col-md-2"></div>
      <select class="form-control custom-select my-1 mr-sm-2" id="keywords" name="keyword_filter"
        onchange="this.form.submit()">
        <option value="">All</option>
        {% for kw in keyword_list %}
        {% if keyword == kw.tag|stringformat:"s" %}
        <option value={{ kw.tag }} selected>{{ kw.tag }}</option>
        {% else %}
        <option value={{ kw.tag }}>{{ kw.tag }}</option>
        {% endif %}
        {% endfor %}
      </select>
</div>
</form>
</div>

<!-- dataset table -->
<div class="container">
<div id="datasets-table" class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead>
      <tr scope="col">
          <th >Title</th>
          <th >Author</th>
          <!--<th >Description</th>-->
          <th >Publication</th>
          <th >Dataset</th>
          <th >Creation Date</th>
          <th >Access</th>
          <th >Keywords</th>
          <th >Models</th>
        </tr>
    </thead>

    {% for job in jobs %}
    <tr scope="row" >
      <td>{{ job.title}}</td>
      <td >{{ job.author }}</td>
      <!--<td > </td>-->
      <td >

        Year: {{ job.year }} <br />
        Journal: {{ job.journal }} <br />
        {% if job.journal_DOI %}
        DOI: <a href="https://doi.org/{{ job.journal_DOI }}">{{ job.journal_DOI }}</a> <br />
        {% endif %}
        {% if job.arxiv_id %}
        Arxiv: <a href="https://arxiv.org/abs/{{ job.arxiv_id }}">{{ job.arxiv_id }}</a>
        {% endif %}


      </td>
      <td >
        {% if job.dataset_DOI %}
        DOI: <a href="https://doi.org/{{ job.dataset_DOI }}">{{ job.dataset_DOI }}</a>
        {% endif %}
      </td>
      <td >{{ job.creation_time }}</td>
      <td >
        {% if job.public == True %}
        Public
        {% else %}
        Private
        {% endif %}
      </td>
      <td>
        {{ job.keywords.all|join:", " }}
      </td>
      <td class="block-cell-center">
        <a class="btn btn-dark"
          href="{% url 'dataset_detail' job.id %}">view</a>        
      </td>
    </tr>
    {% endfor %}

  </table>
</div>
</div>

{% endblock content %}

src/compasweb/templates/compasweb/published_job/model_detail.html
{% extends 'compasweb/base/base.html' %}
{% load static %}

{% block page_header %}
<h1>Published COMPAS Models</h1>
{%endblock page_header%}

{% block content %}

<!-- Dataset information card on the top -->

  <div class="d-flex justify-content-start align-items-stretch flex-wrap">
    <div class="card">
      <h3 class="card-header">Dataset</h3>
      <div class="card-body">
        <p class="p-text-md">
          <div class="div-text-sm"><span class="div-text-sm-underline">Title:</span> {{ datasetmodel.compasjob.title }}</div>
          <div class="div-text-sm"><span class="div-text-sm-underline">Author:</span> {{ datasetmodel.compasjob.author }}</div>
          <div class="div-text-sm"><span class="div-text-sm-underline">Creation Date:</span> {{ datasetmodel.compasjob.creation_time }}</div>
          <div class="div-text-sm"><span class="div-text-sm-underline">Description:</span> {{ datasetmodel.compasjob.description }}</div>
      </p>
      </div>
    </div>

    <div class="card">
      <h3 class="card-header">Model</h3>
      <div class="card-body">
        <p class="p-text-md">
          <div class="div-text-sm"><span class="div-text-sm-underline">Model</span> {{ datasetmodel.compasmodel.name }}</div>
          <div class="div-text-sm"><span class="div-text-sm-underline">Summary:</span> {{ datasetmodel.compasmodel.summary }}</div>
      </p>
      </div>
    </div>

  </div>


    

<!-- title -->
<div class="title-md">
    <h2 class="text-left ">Details</h2>
</div>

<!-- tabs -->


<div class='breadcrumbs'>
  <ul class="nav nav-tabs justify-content-start" id="modeldetailTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">
      Description
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="setting-tab" data-toggle="tab" href="#setting" role="tab" aria-controls="setting" aria-selected="false">COMPAS Settings</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="statistics-tab" data-toggle="tab" href="#statistics" role="tab" aria-controls="statistics" aria-selected="false">Key Statistics</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="visualization-tab" data-toggle="tab" href="#visualization" role="tab" aria-controls="visualization" aria-selected="false">Visualization</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="download-tab" data-toggle="tab" href="#download" role="tab" aria-controls="download" aria-selected="false">Download</a>
  </li>
</ul>
</div>

<!-- tabs contents -->
<div class="tab-content" id="modeldetailTabContent">

<!--description content-->
  <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
    {{ datasetmodel.compasmodel.description | linebreaks }}
  </div>


  <div class="tab-pane fade" id="setting" role="tabpanel" aria-labelledby="setting-tab">
 <!-- {{ compas_setting | linebreaks }} -->
   <p class="tab-content-text"><span class="div-text-sm-underline">sdfsfds of downloadable files</span>: </p>

  </div>

  <div class="tab-pane fade" id="statistics" role="tabpanel" aria-labelledby="statistics-tab">
      <ul class="tab-content-text">
      {% for key, value in stats.items %}
          <li class="tab-list">{{ key }}: {{ value }}</li>
      {% endfor %}
      </ul>
  </div>

    <div class="tab-pane fade" id="visualization" role="tabpanel" aria-labelledby="visualization-tab">
      {{ react_menu|json_script:"menu_list" }}
      {{ kwargs_id|json_script:"id" }}

    </div>

  <div class="tab-pane fade" id="download" role="tabpanel" aria-labelledby="download-tab">
    <p class="tab-content-text"><span class="div-text-sm-underline">Summary of downloadable files</span>: </p>

      <ol class="tab-content-text">
         {% for file in download_files %}
            <li class="tab-list"><a  href="{{ file.file.url }}" download="{{ file }}">{{ file }}</a></li>
         {% endfor %}

      </ol>
  </div>
</div>

<div>
  <a class="btn btn-dark btn-nav-back"
                        href="{% url 'dataset_detail' datasetmodel.compasjob.id %}">Back to Models</a>
</div>
</div>

<script src='{% static "compasweb/js/bundle.js" %}'></script>
{% endblock content %}